;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname exercise_441) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
; Exercise 441.

(define (quick-sort< alon)
  (cond
    [(empty? alon) '()]
    [(empty? (rest alon)) alon]
    [else (local ((define pivot (first alon)))
            (append (quick-sort< (smallers (rest alon) pivot))
                    (list pivot)
                    (quick-sort< (largers (rest alon) pivot))))]))
 
; [List-of Number] Number -> [List-of Number]
(define (largers alon n)
  (cond
    [(empty? alon) '()]
    [else (if (> (first alon) n)
              (cons (first alon) (largers (rest alon) n))
              (largers (rest alon) n))]))

; [List-of Number] Number -> [List-of Number]
(define (smallers l n)
  (cond
    [(empty? l) '()]
    [else (if (<= (first l) n)
              (cons (first l) (smallers (rest l) n))
              (smallers (rest l) n))]))

; Evaluate by hand.
(quick-sort< (list 10 6 8 9 14 12 3 11 14 16 2))

#;
(append (quick-sort< (smallers (list 6 8 9 14 12 3 11 14 16 2) 10))
        (list 10)
        (quick-sort< (largers (list 6 8 9 14 12 3 11 14 16 2) 10)))

(append (quick-sort< (list 6 8 9 3 2))
        (list 10)
        (quick-sort< (list 14 12 11 14 16)))

#;
(append (append (quick-sort< (smallers (list 8 9 3 2) 6))
                (list 6)
                (quick-sort< (largers (list 8 9 3 2) 6)))
        (list 10)
        (append (quick-sort< (smallers (list 12 11 14 16) 14))
                (list 14)
                (quick-sort< (largers (list 12 11 14 16) 14))))

(append (append (quick-sort< (list 3 2))
                (list 6)
                (quick-sort< (list 8 9)))
        (list 10)
        (append (quick-sort< (list 12 11))
                (list 14)
                (quick-sort< (list 14 16))))
#;
(append (append (append (quick-sort< (smallers (list 2) 3))
                        (list 3)
                        (quick-sort< (largers (list 2)  3)))
                (list 6)
                (append (quick-sort< (smallers (list 9) 8))
                        (list 8)
                        (quick-sort< (largers (list 9) 8))))
        (list 10)
        (append (append (quick-sort< (smallers (list 11) 12))
                        (list 12)
                        (quick-sort< (largers (list 11) 12)))
                (list 14)
                (append (quick-sort< (smallers (list 16) 14))
                        (list 14)
                        (quick-sort< (largers (list 16) 14)))))

(append (append (append (quick-sort< (list 2))
                        (list 3)
                        (quick-sort< '()))
                (list 6)
                (append (quick-sort< '())
                        (list 8)
                        (quick-sort< (list 9))))
        (list 10)
        (append (append (quick-sort< (list 11))
                        (list 12)
                        (quick-sort< '()))
                (list 14)
                (append (quick-sort< '())
                        (list 14)
                        (quick-sort< (list 16)))))

(append (append (append (list 2)
                        (list 3)
                        '())
                (list 6)
                (append '()
                        (list 8)
                        (list 9)))
        (list 10)
        (append (append (list 11)
                        (list 12)
                        '())
                (list 14)
                (append '()
                        (list 14)
                        (list 16))))

(append (append  (list 2 3)
                 (list 6)
                 (list 8 9))
        (list 10)
        (append (list 11 12)
                (list 14)
                (list 14 16)))

(append (list 2 3 6 8 9)
        (list 10)
        (list 11 12 14 14 16))

(list 2 3 6 8 9 10 11 12 14 14 16)
        

; Show only those lines that introduce a new recursive call to quick-sort<.
; How many recursive applications of quick-sort< are required?
; - 14 applications of quick-sort<
; How many recursive applications of the append function? Suggest a general rule for a list of length n.
; - 6 applications of append
; - Use generative recursion when the list is larger than 10

; Evaluate by hand. 
(quick-sort< (list 1 2 3 4 5 6 7 8 9 10 11 12 13 14))

#;
(append (quick-sort< (smallers (list 2 3 4 5 6 7 8 9 10 11 12 13 14) 1))
        (list 1)
        (quick-sort< (largers  (list 2 3 4 5 6 7 8 9 10 11 12 13 14) 1)))

(append (quick-sort< '())
        (list 1)
        (quick-sort< (list 2 3 4 5 6 7 8 9 10 11 12 13 14)))

#;
(append '()
        (list 1)
        (append (quick-sort< (smallers (list 3 4 5 6 7 8 9 10 11 12 13 14) 2))
                (list 2)
                (quick-sort< (largers (list 3 4 5 6 7 8 9 10 11 12 13 14) 2))))

(append '()
        (list 1)
        (append (quick-sort< '())
                (list 2)
                (quick-sort< (list 3 4 5 6 7 8 9 10 11 12 13 14))))

#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append (quick-sort< (smallers (list 4 5 6 7 8 9 10 11 12 13 14) 3))
                        (list 3)
                        (quick-sort< (largers (list 4 5 6 7 8 9 10 11 12 13 14) 3)))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append (quick-sort< '())
                        (list 3)
                        (quick-sort< (list 4 5 6 7 8 9 10 11 12 13 14)))))

#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append (quick-sort< (smallers (list 5 6 7 8 9 10 11 12 13 14) 4))
                                (list 4)
                                (quick-sort< (largers (list 5 6 7 8 9 10 11 12 13 14) 4))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append (quick-sort< '())
                                (list 4)
                                (quick-sort< (list 5 6 7 8 9 10 11 12 13 14))))))

#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append (quick-sort< (smallers (list 6 7 8 9 10 11 12 13 14) 5))
                                        (list 5)
                                        (quick-sort< (largers (list 6 7 8 9 10 11 12 13 14) 5)))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append (quick-sort< '())
                                        (list 5)
                                        (quick-sort< (list 6 7 8 9 10 11 12 13 14)))))))

#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append (quick-sort< (smallers (list 7 8 9 10 11 12 13 14) 6))
                                                (list 6)
                                                (quick-sort< (largers (list 7 8 9 10 11 12 13 14) 6))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append (quick-sort< '())
                                                (list 6)
                                                (quick-sort< (list 7 8 9 10 11 12 13 14))))))))
#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append (quick-sort< (smallers (list 8 9 10 11 12 13 14) 7))
                                                        (list 7)
                                                        (quick-sort< (largers (list 8 9 10 11 12 13 14) 7)))))))))
                                                

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append (quick-sort< '())
                                                        (list 7)
                                                        (quick-sort< (list 8 9 10 11 12 13 14)))))))))
#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append (quick-sort< (smallers (list 9 10 11 12 13 14) 8))
                                                                (list 8)
                                                                (quick-sort< (largers (list 9 10 11 12 13 14) 8))))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (quick-sort< (list 9 10 11 12 13 14))))))))))
#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append (quick-sort< (smallers (list 10 11 12 13 14) 9))
                                                                        (list 9)
                                                                        (quick-sort< (largers (list 10 11 12 13 14) 9)))))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '())
                                                                        (list 9)
                                                                        (quick-sort< (list 10 11 12 13 14))))))))))
#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append (quick-sort< (smallers (list 11 12 13 14) 10))
                                                                                (list 10)
                                                                                (quick-sort< (largers (list 11 12 13 14) 10))))))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (quick-sort< (list 11 12 13 14))))))))))))
#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append (quick-sort< (smallers (list 12 13 14) 11))
                                                                                        (list 11)
                                                                                        (quick-sort< (largers (list 12 13 14) 11)))))))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append '()
                                                                                        (list 11)
                                                                                        (quick-sort< (list 12 13 14)))))))))))))
                                                                                                

#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append '()
                                                                                        (list 11)
                                                                                        (append (quick-sort< (smallers (list 13 14) 12))
                                                                                                (list 12)
                                                                                                (quick-sort< (largers (list 13 14) 12))))))))))))))
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append '()
                                                                                        (list 11)
                                                                                        (append '()
                                                                                                (list 12)
                                                                                                (quick-sort< (list 13 14))))))))))))))
#;
(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append '()
                                                                                        (list 11)
                                                                                        (append '()
                                                                                                (list 12)
                                                                                                (append (quick-sort< (smallers (list 14) 13))
                                                                                                        (list 13)
                                                                                                        (quick-sort< (largers (list 14) 13)))))))))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append '()
                                                                                        (list 11)
                                                                                        (append '()
                                                                                                (list 12)
                                                                                                (append '()
                                                                                                        (list 13)
                                                                                                        (quick-sort< (list 14)))))))))))))))

(append '()
        (list 1)
        (append '()
                (list 2)
                (append '()
                        (list 3)
                        (append '()
                                (list 4)
                                (append '()
                                        (list 5)
                                        (append '()
                                                (list 6)
                                                (append '()
                                                        (list 7)
                                                        (append '()
                                                                (list 8)
                                                                (append '()
                                                                        (list 9)
                                                                        (append '()
                                                                                (list 10)
                                                                                (append '()
                                                                                        (list 11)
                                                                                        (append '()
                                                                                                (list 12)
                                                                                                (append '()
                                                                                                        (list 13)
                                                                                                        (list 14))))))))))))))

; How many recursive applications of quick-sort< are required?
; - 14
; How many recursive applications of append? 28
; - 28
; Does this contradict the first part of the exercise?
; - yes the list is already sorted but runs through the full count of the list, it tkaes longer to do it this way


